BoxLayout:
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: "Bb.png"
    BoxLayout:
        orientation:'vertical'
        size_hint:( 1, .3)
        pos_hint:{'right':1, 'y':0.1}
        Label:
        TextInput:
            id:usr
            multiline:False
        TextInput:
            id:password
            multiline:False

        Button:
            text: "Login"
            background_color: 1,233,32,95
